"""BellGuard 15:00 webhook preview generator.

No-send utility only. It reads the BellGuard main candidate file generated by
Codex and writes a preview under C:/Coding/data/closingbell/health.

Usage:
    python scripts/render_webhook_preview.py --date 2026-05-15
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd


REPO = Path(__file__).resolve().parents[1]
LATEST = REPO / "data" / "closingbell" / "online_v2" / "latest"


def _resolve_bellguard_top3() -> Path:
    """우선순위: bellguard_pricecap_1y > bellguard_1y"""
    pc = LATEST / "bellguard_pricecap_1y" / "bellguard_pricecap_top3_latest.csv"
    if pc.exists():
        return pc
    return LATEST / "bellguard_1y" / "bellguard_top3_latest.csv"


BELLGUARD_TOP3 = _resolve_bellguard_top3()
V2_RECORD_TOP3 = LATEST / "v2_record_1y" / "v2_record_top3_latest.csv"
HEALTH_DIR = Path(r"C:\Coding\data\closingbell\health")

FORBIDDEN_TERMS = [
    "추천",
    "확정 매수",
    "무조건",
    "승률 보장",
    "자동매수",
    "자동 매수",
    "안전한 종목",
    "보장",
    "확실히",
    "필승",
]

LIGHT_LABELS = {
    "GREEN": ("🟢", "녹색"),
    "YELLOW": ("🟡", "노랑"),
    "ORANGE": ("🟠", "주황"),
    "RED": ("🔴", "빨강"),
    "GRAY": ("⚪", "회색"),
}


def norm_code(value: Any) -> str:
    text = str(value or "").strip()
    if text.endswith(".0"):
        text = text[:-2]
    return text.zfill(6)


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default
        return float(value)
    except Exception:
        return default


def pct_text(value: Any) -> str:
    return f"{safe_float(value):+.1f}%"


def eok_text(value: Any) -> str:
    return f"{safe_float(value) / 100_000_000.0:,.1f}억"


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path, encoding="utf-8-sig")


def validate_forbidden(message: str) -> list[str]:
    """금지어 검사 + 부정형 화이트리스트 (예: "매수 추천이 아닙니다" 같은 안내는 통과)."""
    import re as _re
    whitelist_prefixes = [
        "매수 추천이 아", "매수 추천은 아", "추천이 아닙니다", "추천이 아니라",
        "추천은 아니며", "추천 아닙니다", "추천 아닌",
    ]
    hits: list[str] = []
    for term in FORBIDDEN_TERMS:
        if term not in message:
            continue
        contexts = _re.findall(rf".{{0,25}}{_re.escape(term)}.{{0,25}}", message)
        bad = [c for c in contexts if not any(w in c for w in whitelist_prefixes)]
        if bad:
            hits.append(term)
    return hits


def render_message(target_date: str, bellguard: pd.DataFrame, v2_record: pd.DataFrame) -> str:
    """가독성·종목정보 중심 메시지. 운영 가드/데이터출처/버전 메타는 제외.

    사용자 피드백 2026-05-17:
        "설득력 있지만 가독성, 종목 정보만"
    """
    divider = "━" * 19
    lines = [
        "🔔 **ClosingBell 15:00 · 벨가드 안정후보 Top3**",
        f"기준일 {target_date}",
        "",
        divider,
        "",
    ]
    if bellguard.empty:
        lines.extend(["(오늘은 표시할 후보 없음)", "", divider, ""])
    else:
        # pricecap_rank 우선, 없으면 bellguard_rank
        for _, row in bellguard.head(3).iterrows():
            rank = int(safe_float(row.get("pricecap_rank") or row.get("bellguard_rank"), 0))
            light = str(
                row.get("bellguard_live_light")
                or row.get("traffic_light")
                or row.get("d1_color")
                or "GRAY"
            ).upper()
            icon, _ = LIGHT_LABELS.get(light, LIGHT_LABELS["GRAY"])
            name = row.get("name") or row.get("stock_label") or "-"
            code = norm_code(row.get("code"))
            market = row.get("market") or "-"
            # 진입가 — pricecap 데이터셋은 entry_price_used / hint 사용
            entry = safe_float(
                row.get("entry_price_used") or row.get("entry_price_1500")
                or row.get("entry_price_hint") or row.get("d0_close"), 0,
            )
            entry_text = f"{int(round(entry)):,}원" if entry > 0 else "-"
            # BellGuard 점수 — 0~1 비율이면 ×100 정규화
            score = safe_float(row.get("bellguard_score") or row.get("source_score"), 0)
            if 0 < score <= 1.0001:
                score *= 100
            score_text = f"{score:.0f}"
            # D0 등락 / 거래대금
            d0_pct = pct_text(row.get("d0_pct_change") or row.get("d0_ret_pct"))
            tv_eok_raw = row.get("d0_trading_value_eok")
            if pd.notna(tv_eok_raw):
                try:
                    d0_value_text = f"{float(tv_eok_raw):,.0f}억"
                except (TypeError, ValueError):
                    d0_value_text = eok_text(row.get("d0_trading_value"))
            else:
                d0_value_text = eok_text(row.get("d0_trading_value"))
            # 근거 / 체크
            reason = str(
                row.get("bellguard_reason_auto")
                or row.get("bellguard_reason")
                or row.get("traffic_reason")
                or ""
            ).strip()
            if not reason or reason.lower() == "nan":
                reason = "—"
            number_emoji = ["1️⃣", "2️⃣", "3️⃣"][rank - 1] if 1 <= rank <= 3 else "•"
            lines.extend([
                f"{number_emoji} {icon} **{name}** · {code} · {market}",
                f"   15시가  {entry_text}",
                f"   D0      {d0_pct}  ·  거래대금 {d0_value_text}",
                f"   점수    {score_text}  ·  근거: {reason}",
                "   체크    VWAP 위 유지 · 전고점 부근 · 거래량 유지",
                "",
            ])
        lines.extend([divider, ""])
    # 마지막 한 줄 — 운영 가드 대신 짧은 안내
    lines.append("매수 추천이 아닙니다 · 차트와 호가 직접 확인 후 판단하세요.")
    if not v2_record.empty:
        lines.append(f"※ 기존 V2 후보 {len(v2_record)}건은 내부 기록으로 별도 보존.")
    return "\n".join(lines).strip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", default="")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    bellguard = read_csv(BELLGUARD_TOP3)
    v2_record = read_csv(V2_RECORD_TOP3)
    if args.date:
        target_date = args.date
    elif not bellguard.empty and "signal_date" in bellguard.columns:
        target_date = str(bellguard["signal_date"].dropna().astype(str).max())
    else:
        target_date = datetime.now().date().isoformat()

    compact = target_date.replace("-", "")
    out_path = Path(args.out) if args.out else HEALTH_DIR / f"webhook_preview_bellguard_1500_{compact}.md"
    json_path = out_path.with_suffix(".json")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    message = render_message(target_date, bellguard, v2_record)
    found = validate_forbidden(message)
    out_path.write_text(message, encoding="utf-8")
    json_path.write_text(
        json.dumps(
            {
                "generated_at": datetime.now().isoformat(timespec="seconds"),
                "target_date": target_date,
                "send_attempted": False,
                "webhook_main_mode": "dual_preview",
                "forbidden_terms_found": found,
                "preview_path": str(out_path),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(json.dumps({"status": "ok", "out": str(out_path), "forbidden_terms_found": found}, ensure_ascii=False))


if __name__ == "__main__":
    main()
